# discourse-sms-login/config/settings.yml
sms_login_enabled:
  default: false
  client: true
tencent_secret_id:
  default: ""
  client: false
tencent_secret_key:
  default: ""
  client: false
sms_template_id:
  default: ""
  client: false
sms_sign_name:
  default: ""
  client: false
verification_code_length:
  default: 6
verification_code_ttl:
  default: 300
max_resend_attempts:
  default: 5